version: '3'

services:

  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_PASSWORD=123456

  filmes-api:
    depends_on:
      - postgresql
    image: lcmuniz/filmes-api:0.0.1-SNAPSHOT
    ports:
      - 8080:8080

