services:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=facam-sa
      - MYSQL_USER=facam
      - MYSQL_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
 
volumes:
  mysql-data:
    